[package]
name = "jewels-rust"
version = "1.0.0"
edition = "2021"
authors = ["Daniel Ivanescu <bytemaniak@proton.me>"]

[[bin]]
name = "jewels-rust"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"

[dependencies.sdl2]
version = "0.35.2"
features = ["image", "mixer", "ttf"]
